using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TournamentTrackerLibrary.Models;

// changing the namespace so that only people having the using statement get the extra clutter that this is gonna craete
// namespace TournamentTrackerLibrary.DataAccess
namespace TournamentTrackerLibrary.DataAccess.TextHelpers
{
    
    
    //Step 3: Find the max ID
    //Step 4: Add the new record with the new ID ie, Max+1S
    //Step 5: Convert the Prizes to a List<String>
    //Step 6: Save the List<String> to the text File


    public static class TextConnectorProcessor
    {

        // if you see the "this" keyword here, it's an extension manager where by the end of the method the full file path is stored back in fileName.
        public static string FullFilePath(this string fileName) // sample filename would be like PrizeModels.csv
        {
            // this method takes the fileName and returns back the entire path -- mergiing with the path in from the app.config

            // the $"" allows us to concatenate strings together
            // here the \\ is the first one is escape haracter amd the second \ is actual backslash
            return $"{ ConfigurationManager.AppSettings["filePath"] }\\{fileName}";
        }

        //Step 1: Load the text file

        // It will take in the full file path from above method and it's gonna load that string  
        public static List<string> LoadFile(this string file) 
        { 
            // this checks if the file doesn't exists in File of system.io namespace then return an empty list
            if (!File.Exists(file))
            {
                return new List<string>();
            }
            //if exists return list of all the lines in the text file
            return File.ReadAllLines(file).ToList();
        }


        //Step 2: Convert the text to a List<Prize Model>

        // This method takes the list of lines generated by the above method and converts it into a list of PrizeModel
        public static List<PrizeModel> ConvertToPrizeModels (this List<string> lines)
        {
            List<PrizeModel> output = new List<PrizeModel>();
            foreach(string line in lines)
            {
                string[] cols = line.Split(',');
                PrizeModel p = new PrizeModel();
                p.Id = int.Parse(cols[0]);
                p.PlaceNumber = int.Parse(cols[1]);
                p.PlaceName = cols[2];
                p.PrizeAmount = decimal.Parse(cols[3]);
                p.PrizePercentage = double.Parse(cols[4]);
                output.Add(p);
            }
            return output;
        }


        //Step 5: Convert the Prizes to a List<String>
        public static void SaveToPrizeFile(this List<PrizeModel> models, string fileName)
        {
            List<string> lines = new List<string>();

            foreach(PrizeModel p in models)
            {
                lines.Add($"{ p.Id },{ p.PlaceNumber },{ p.PlaceName },{ p.PrizeAmount },{ p.PrizePercentage }");
            }

            File.WriteAllLines(fileName.FullFilePath(), lines);
        }
    }
}
